"""
Quick test to show calibrated HSV ranges and help debug detection issues
"""

print("🔍 Camera Detection Debug Helper")
print("="*60)
print("\nFrom your last calibration:")
print("\nGOLD:")
print("  Mean HSV: H=56.8, S=246.2, V=33.3")
print("  Range: [ 10 166   0] - [103 255 147]")
print("\nSILVER:")
print("  Mean HSV: H=63.5, S=236.0, V=32.5")
print("  Range: [ 15 151   0] - [111 255 144]")
print("\nBRONZE:")
print("  Mean HSV: H=56.9, S=241.8, V=31.5")
print("  Range: [  2 160   0] - [110 255 144]")

print("\n" + "="*60)
print("⚠️  ISSUE DETECTED:")
print("="*60)
print("All three chips have VERY SIMILAR HSV values!")
print("  - All H (Hue) values are between 56-63 (greenish-yellow)")
print("  - All S (Saturation) values are very high (236-246)")
print("  - All V (Value) values are very low (31-33)")
print("\nThis suggests:")
print("  1. The lighting conditions are making all chips look similar")
print("  2. The chips might be reflecting the same background color")
print("  3. The camera exposure might be too low (V=31-33 is very dark)")

print("\n" + "="*60)
print("💡 SOLUTIONS:")
print("="*60)
print("1. Improve lighting - add more bright white light")
print("2. Adjust camera exposure/brightness settings")
print("3. Use different colored backgrounds (not green)")
print("4. Make sure chips are different colors (Gold/Silver/Bronze)")
print("5. Recalibrate with better lighting")

print("\n" + "="*60)
print("🔧 QUICK FIX - Try these settings:")
print("="*60)
print("If your chips are actually:")
print("  - GOLD (yellow/gold color)")  
print("  - SILVER (white/gray color)")
print("  - BRONZE (brown/copper color)")
print("\nThen expected HSV ranges should be:")
print("  GOLD:   H=20-35, S=100-255, V=100-255")
print("  SILVER: H=0-180, S=0-50, V=100-255")
print("  BRONZE: H=10-20, S=100-255, V=50-200")
print("\nYour current values show V=31-33 which is VERY DARK!")
print("Try increasing camera brightness/exposure")
